apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpi

resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - redis.yaml
  # Uncomment to use the sqlite backend with a persistent volume instead of redis.
  # - pvc.yaml
