apiVersion: v1
kind: Service
metadata:
  name: gpi
  namespace: gpi
  labels:
    app.kubernetes.io/name: gpi
    app.kubernetes.io/part-of: gpi
spec:
  selector:
    app: gpi
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
