//go:build ignore

// Command gen regenerates imports.go by scanning internal/cloud/ for every
// sub-package that defines and registers a cloud provider (has a provider.go
// whose init() calls cloud.Register). Run with:
//
//	cd internal/cloud/imports && go run gen.go
//
// or simply `go generate ./internal/cloud/imports`.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root := filepath.Join("..") // internal/cloud
	entries, err := os.ReadDir(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read cloud dir:", err)
		os.Exit(1)
	}
	var clouds []string
	for _, e := range entries {
		if !e.IsDir() || e.Name() == "imports" {
			continue
		}
		provider := filepath.Join(root, e.Name(), "provider.go")
		data, err := os.ReadFile(provider)
		if err != nil {
			continue // not a cloud package
		}
		if !strings.Contains(string(data), "cloud.Register(") {
			continue
		}
		clouds = append(clouds, e.Name())
	}
	sort.Strings(clouds)

	var b strings.Builder
	b.WriteString("// Code generated by gen.go; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Package imports is the single registration point for every supported cloud.\n")
	b.WriteString("// Blank-importing it runs each cloud provider's init(), which registers the\n")
	b.WriteString("// provider, its catalog metadata source and its pricing in one place. Consumers that\n")
	b.WriteString("// need clouds (the gpi binary, tests) import only this package.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate after adding a cloud:\n")
	b.WriteString("//\n")
	b.WriteString("//\tgo generate ./internal/cloud/imports\n")
	b.WriteString("package imports\n\n")
	b.WriteString("import (\n")
	for _, c := range clouds {
		fmt.Fprintf(&b, "\t_ %q\n", "github.com/acmestack/gpi/internal/cloud/"+c)
	}
	b.WriteString(")\n")

	if err := os.WriteFile("imports.go", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write imports.go:", err)
		os.Exit(1)
	}
	fmt.Println("imports.go regenerated with clouds:", strings.Join(clouds, ", "))
}
